version: '3.7'

services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      PRISMA_DATABASE_URL: "postgresql://user:password@database:5432/database"

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: